### ISSUE TITLE
Extract vertices data (X,Y,Z) from a *.fbx

### ISSUE THREAD

**Issue by pmorshed** [DomCR/MeshIO#13]
Hi. How can I extract vertices data (X,Y,Z list) from a *.fbx 3D model via MeshIO?
For example, suppose I have a box in the fbx file (attached) and I want to extract the coordinates of its vertices in CSV format. What should I do?
[box1.zip](https://github.com/DomCR/MeshIO/files/10246112/box1.zip)

**Comment by DomCR** [comment]
Hi @pmorshed,

to extract the vertices you just need to access to the `Scene.Nodes` and look for the `Element` that you are looking for, here is an example:

```CSharp
Scene scene = FbxReader.Read(test, ErrorLevel.Checked);

//Iterate throgh all the nodes in the scene
foreach (Node item in scene.Nodes)
{
      //Here you can apply filter if you know the name of the node
      //Each node can contain geometric elements so you have to look in the elements contained in the main node
      foreach (Element c in item.Children)
      {
	      //Check if the element is a geometric type
	      if (!(c is Geometry geometry))
		      continue;
      
	      //Get the vertices of the element
	      List<CSMath.XYZ> vertices = geometry.Vertices;
      }
}
```

**Comment by pmorshed** [comment]
> Hi @pmorshed,
> 
> to extract the vertices you just need to access to the `Scene.Nodes` and look for the `Element` that you are looking for, here is an example:
> 
> ```cs
> Scene scene = FbxReader.Read(test, ErrorLevel.Checked);
> 
> //Iterate throgh all the nodes in the scene
> foreach (Node item in scene.Nodes)
> {
>       //Here you can apply filter if you know the name of the node
>       //Each node can contain geometric elements so you have to look in the elements contained in the main node
>       foreach (Element c in item.Children)
>       {
> 	      //Check if the element is a geometric type
> 	      if (!(c is Geometry geometry))
> 		      continue;
>       
> 	      //Get the vertices of the element
> 	      List<CSMath.XYZ> vertices = geometry.Vertices;
>       }
> }
> ```

Hi. Thanks for the quick reply. I tried it but it didn't give any output. Have you tried it yourself?

**Comment by DomCR** [comment]
You are right, the problem is that the mesh is inside another node, so 2 levels `Node.Node.Geometry` with recursion is easy to pick all geometries, try this:

```CSharp
public static IEnumerable<Geometry> GetAllGeometryInTheScene(string path)
{
	Scene scene = FbxReader.Read(path, ErrorLevel.Checked);
	List<Geometry> geometries = new List<Geometry>();

	//Iterate throgh all the nodes in the scene
	foreach (Node item in scene.Nodes)
	{
		//Here you can apply filter if you know the name of the node

		geometries.AddRange(GetAllGeometryInTheNode(item));
	}

	return geometries;
}

public static List<Geometry> GetAllGeometryInTheNode(Node node)
{
	List<Geometry> list = new List<Geometry>();
	//Each node can contain geometric elements so you have to look in the elements contained in the main node
	foreach (Element c in node.Children)
	{
		//Check if the element is a geometric type
		if (c is Geometry geometry)
		{
			list.Add(geometry);
			continue;
		}
		else if (c is Node n)
		{
			list.AddRange(GetAllGeometryInTheNode(n));
		}
	}

	return list;
}
```

I've tried with your document and it worked find.

**Comment by pmorshed** [comment]
Yes, works like a charm. Thanks so much
