### ISSUE TITLE
Force dot instead of comma for decimal number separator in ASCII formats.

### ISSUE THREAD

**Issue by Biliogadafr** [DomCR/MeshIO#25]
When I was trying to use this library from Unity I noticed that exported ASCII STL files looked incorrectly. 
For example vertex looks like that:
vertex 3,488124 8,464913 11
So the result was corrupted:
![изображение](https://github.com/DomCR/MeshIO/assets/10543859/35a6e27b-1ffa-473b-8459-097cde3adf99)
To fix this problem I changed StlWriter as described here https://groups.google.com/g/dotnetdevelopment/c/weQuHv-C-XE 
```csharp
		public void WriteAscii(Mesh mesh)
		{
			this.validate(mesh);
			
			using (TextWriter tw = new StreamWriter(this._stream.Stream, new UTF8Encoding(false)))
			{
				System.Globalization.NumberFormatInfo nfi = new();
				nfi.NumberDecimalSeparator = ".";

				tw.WriteLine($"solid {mesh.Name}");

				LayerElementNormal normals = mesh.Layers.GetLayer<LayerElementNormal>();
				for (int i = 0; i < mesh.Polygons.Count; i++)
				{
					XYZ normal = normals.Normals[i];

					tw.WriteLine($"  facet normal {normal.X.ToString(nfi)} {normal.Y.ToString(nfi)} {normal.Z.ToString(nfi)}");

					tw.WriteLine($"    outer loop");

					foreach (int item in (Triangle)mesh.Polygons[i])
					{
						var v = mesh.Vertices[item];

						tw.WriteLine($"      vertex {v.X.ToString(nfi)} {v.Y.ToString(nfi)} {v.Z.ToString(nfi)}");
					}

					tw.WriteLine($"    endloop");
					tw.WriteLine($"  endfacet");
				}

				tw.WriteLine($"endsolid {mesh.Name}");
			}
		}
```
With this changes result looks as intended 
![изображение](https://github.com/DomCR/MeshIO/assets/10543859/4e522bad-9e7b-4058-9240-6616475565d8)
I'm not sure that this is the best solution, so I decided to create an issue here.

**Comment by DomCR** [comment]
Hi @Biliogadafr 

Your solution looks good! thanks for that.

If you want, open a PR with this implementation, I would like to investigate a little more about this issue but we can continue the conversation in the code review.

Right now the solution seems to work but I would change how you initialize the `System.Globalization.NumberFormatInfo`, this would be best if is in the constructor of the reader class, just to make sure that is initialized only once for all the possible uses, also assigning the separator "manually" is something that I would try to avoid, I'll explore a little with the culture settings.

Thanks for your support!
