### ISSUE TITLE
Can't export to FBX

### ISSUE THREAD

**Issue by Biliogadafr** [DomCR/MeshIO#26]
Hello. 
I was trying to export my mesh to fbx with this code:
(Mesh was constructed from Unity model and I was able to successfully export it to STL earlier)
```csharp
        MeshIO.Scene scene = new();
        scene.RootNode.Nodes.Add(convertedMesh);
        string pathfBX = System.IO.Path.Combine("D:/test", "fbx_bin.fbx");
        using(MeshIO.FBX.FbxWriter writer = new MeshIO.FBX.FbxWriter(pathfBX, scene)) {
            writer.Write(MeshIO.FBX.FbxFileFormat.Binary);
        }
```
This generates exception:
```
InvalidOperationException: Nullable object must have a value.
System.Nullable`1[T].get_Value () (at <88e4733ac7bc4ae1b496735e6b83bbd3>:0)
MeshIO.FBX.Converters.SceneConverterBase.buildObjectsNode () (at MeshIO.FBX/Converters/SceneConverterBase.cs:171)
MeshIO.FBX.Converters.SceneConverterBase.ToRootNode () (at MeshIO.FBX/Converters/SceneConverterBase.cs:82)
MeshIO.FBX.FbxRootNode.CreateFromScene (MeshIO.Scene scene, MeshIO.FBX.FbxVersion version) (at MeshIO.FBX/FbxRootNode.cs:28)
MeshIO.FBX.FbxWriter.Write (MeshIO.FBX.FbxFileFormat fileFormat) (at MeshIO.FBX/FbxWriter.cs:104)
```
![изображение](https://github.com/DomCR/MeshIO/assets/10543859/2d717576-defe-4a93-8977-1d0f7ad097af)
If I try to add some ID like this:
```csharp
        convertedMesh.Id = 0;
```
then exception changes to this:
```
FbxException: Invalid property type System.UInt64, at Geometry/Objects[0]
MeshIO.FBX.FbxBinaryWriter.WriteProperty (System.Object obj, System.Int32 id) (at MeshIO.FBX/Writers/FbxBinaryWriter.cs:195)
MeshIO.FBX.FbxBinaryWriter.WriteNode (MeshIO.FBX.FbxRootNode document, MeshIO.FBX.FbxNode node) (at MeshIO.FBX/Writers/FbxBinaryWriter.cs:254)
MeshIO.FBX.FbxBinaryWriter.WriteNode (MeshIO.FBX.FbxRootNode document, MeshIO.FBX.FbxNode node) (at MeshIO.FBX/Writers/FbxBinaryWriter.cs:271)
MeshIO.FBX.FbxBinaryWriter.Write () (at MeshIO.FBX/Writers/FbxBinaryWriter.cs:60)
MeshIO.FBX.FbxWriter.Write (MeshIO.FBX.FbxFileFormat fileFormat) (at MeshIO.FBX/FbxWriter.cs:109)
```
![изображение](https://github.com/DomCR/MeshIO/assets/10543859/6fbb811d-a3f5-4009-aabd-6b8dacad781f)

If I change to ACSII, then I get some file, which apps can not open:
[fbx_ascii.zip](https://github.com/DomCR/MeshIO/files/11840893/fbx_ascii.zip)

Unfortunately I was not able to find examples of saving FBX with this library. Even MeshIO.STL.Tests just creates empty scene without trying to save actual model. So I'm not sure if I did something wrong, or support for fbx format is incomplete.

**Comment by DomCR** [comment]
Hi @Biliogadafr 

The fbx support is still in development, I was trying to push the [primitives](https://github.com/DomCR/MeshIO/pull/21) first so it is easier to generate some geometry for testing.

The implementation of the feature **code to 3d** is not properly tested nor implemented, I'll open a branch to add the needed test for all the different formats and start with the fbx implementation.
