### ISSUE TITLE
Nuget Package

### ISSUE THREAD

**Issue by ds5678** [DomCR/MeshIO#4]
Hi! This is awesome what you're doing here. I was thinking about maybe using your MeshIO.FBX in my [AssetRipper](https://github.com/ds5678/AssetRipper) project. Would you be willing to publish a nuget package for it?

**Comment by DomCR** [comment]
Hi @ds5678,

thanks for the suggestion, I'll look to release the first version of this library in NugetPackage.
The project is in an early stage, but if you start using it and you find any bug, error or an idea to add as a feature don doubt to open an issue.

**Comment by ds5678** [comment]
Hi Dom, do you have Discord? There's a link to my server on AssetRipper repository page. If you're willing, I would like to pass some thoughts back and forth.

**Comment by DomCR** [comment]
Hi @ds5678, 
I've publish the first version of the Package, notice that is an alpha version and there is only the fbx library.

**Comment by ds5678** [comment]
@DomCR Do you have an opinion on these changes?
